
package Gui;

import buenprovecho.BuenProvecho;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import restaurante.Restaurante;

/**
 * Project:BuenProvecho
 * @author Marlene Vásquez
 * class: BuenProvecho
 * date : 07-jun-2015
 * time : 20:35:55
 */
public class BuenProvecho_GUI extends javax.swing.JFrame {
// Obtener la única instancia de la clase BuenProvecho (patrón sigleton)
        BuenProvecho aComer = BuenProvecho.getInstance(); 
        
         ArrayList listaTelefonos= new ArrayList();
    /**
     * Creates new form BuenProvecho_GUI
     */
    public BuenProvecho_GUI() {
        initComponents();
        this.invisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gestion = new javax.swing.JTabbedPane();
        JP_Responsables = new javax.swing.JPanel();
        CrearResponsable = new javax.swing.JButton();
        jb_listaRes = new javax.swing.JButton();
        jp_imageResponsables = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jp_ListarRes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_listarRes = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jp_DarAlta = new javax.swing.JPanel();
        resgistrarResponsable = new javax.swing.JButton();
        jt_ClaveRes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombreRes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_CorreoRes = new javax.swing.JTextField();
        Restaurantes_menu = new javax.swing.JPanel();
        jb_RegistrarRes = new javax.swing.JButton();
        jb_verResPendientes = new javax.swing.JButton();
        jb_confirmarReg = new javax.swing.JButton();
        jb_consultarRes = new javax.swing.JButton();
        jb_Actualizar = new javax.swing.JButton();
        jP_RegistrarRes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jt_nomResp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_nombreRest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_provincia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt_localidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt_telefono = new javax.swing.JTextField();
        jb_registar = new javax.swing.JButton();
        jP_Confirmar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jt_telfRestaurante = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_ListaSinConfirm = new javax.swing.JTextArea();
        jB_ConfrimarRegistro = new javax.swing.JButton();
        jB_AgregarT = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_listasTelefonos = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jP_Pendientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_ListarPendientes = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        JP_VerRestResp = new javax.swing.JPanel();
        jL_respCons = new javax.swing.JLabel();
        JT_RESP_CONS = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_Listar_Mis_Rest = new javax.swing.JTextArea();
        jB_ConsultarResp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jP_ActualizarDatosRest = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jt_acTeltf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jt_horario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jt_tipoCocina = new javax.swing.JTextField();
        jt_precioMedio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jT_DescripcionRes = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        JP_imageRestaurante = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        JP_Reservas = new javax.swing.JPanel();
        JP_ImageReservas = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        JP_SolicitarReserva = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jt_solResNombreU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jt_solReserCorreo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jt_solReserTelfUs = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jt_solReserTelfRes = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jt_minutos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jC_mes = new javax.swing.JComboBox();
        jC_dia = new javax.swing.JComboBox();
        jt_NComensales = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jt_Hora = new javax.swing.JTextField();
        JB_SolicitarReserva = new javax.swing.JButton();
        JP_ConfirmarReserva = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jt_confReserCodigo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jt_confResrTelf = new javax.swing.JTextField();
        jB_ConfirmarReserva = new javax.swing.JButton();
        jP_verReserva = new javax.swing.JPanel();
        jt_verResrTelf1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jB_VerReserva = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jT_verReserSel = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jP_AnularReserva = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jt_AnularReserCodigo = new javax.swing.JTextField();
        jB_AnularRes = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jt_AnularResertelefono = new javax.swing.JTextField();
        jb_ConfirmarReserva = new javax.swing.JButton();
        jb_VerReservas = new javax.swing.JButton();
        jb_AnularReserva = new javax.swing.JButton();
        jb_AnularReservasPasadas = new javax.swing.JButton();
        jb_SolicitarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion.setForeground(new java.awt.Color(255, 153, 0));
        Gestion.setMinimumSize(new java.awt.Dimension(800, 480));

        JP_Responsables.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_Responsables.setForeground(new java.awt.Color(255, 153, 0));
        JP_Responsables.setMinimumSize(new java.awt.Dimension(800, 450));
        JP_Responsables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearResponsable.setText("Nuevo Responsable");
        CrearResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearResponsableActionPerformed(evt);
            }
        });
        JP_Responsables.add(CrearResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 250, 60));

        jb_listaRes.setText("Ver Responsables");
        jb_listaRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listaResActionPerformed(evt);
            }
        });
        JP_Responsables.add(jb_listaRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 250, 60));

        jp_imageResponsables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/tactil.jpg"))); // NOI18N
        jp_imageResponsables.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 390));

        JP_Responsables.add(jp_imageResponsables, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 410));

        jp_ListarRes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_ListarRes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jT_listarRes.setColumns(20);
        jT_listarRes.setRows(5);
        jScrollPane1.setViewportView(jT_listarRes);

        jp_ListarRes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 380, 240));

        jLabel38.setText("Restaurantes");
        jp_ListarRes.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        JP_Responsables.add(jp_ListarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 470, 300));

        jp_DarAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_DarAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resgistrarResponsable.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        resgistrarResponsable.setText("Dar de alta");
        resgistrarResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resgistrarResponsableActionPerformed(evt);
            }
        });
        jp_DarAlta.add(resgistrarResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 210, 30));
        jp_DarAlta.add(jt_ClaveRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 240, -1));

        jLabel1.setText("Clave:");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_DarAlta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        jLabel2.setText("Nombre :");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_DarAlta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));
        jp_DarAlta.add(jt_nombreRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 240, -1));

        jLabel3.setText("Correo:");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp_DarAlta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 30));
        jp_DarAlta.add(jt_CorreoRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 240, -1));

        JP_Responsables.add(jp_DarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 480, 270));

        Gestion.addTab("Responsables", new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icon.png")), JP_Responsables); // NOI18N

        Restaurantes_menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Restaurantes_menu.setForeground(new java.awt.Color(255, 153, 0));
        Restaurantes_menu.setMinimumSize(new java.awt.Dimension(800, 450));
        Restaurantes_menu.setName(""); // NOI18N
        Restaurantes_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_RegistrarRes.setText("Registrar Restaurante");
        jb_RegistrarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_RegistrarResActionPerformed(evt);
            }
        });
        Restaurantes_menu.add(jb_RegistrarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 280, 60));

        jb_verResPendientes.setText(" Restaurantes Pendientes");
        jb_verResPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verResPendientesActionPerformed(evt);
            }
        });
        Restaurantes_menu.add(jb_verResPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 280, 60));

        jb_confirmarReg.setText("Confirmar Registro");
        jb_confirmarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_confirmarRegActionPerformed(evt);
            }
        });
        Restaurantes_menu.add(jb_confirmarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 280, 60));

        jb_consultarRes.setText("Ver Restaurantes de un Responsables");
        jb_consultarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_consultarResActionPerformed(evt);
            }
        });
        Restaurantes_menu.add(jb_consultarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 280, 60));

        jb_Actualizar.setText("Actualizar Datos Restaurantes");
        jb_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ActualizarActionPerformed(evt);
            }
        });
        Restaurantes_menu.add(jb_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 280, 60));

        jP_RegistrarRes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_RegistrarRes.setMinimumSize(new java.awt.Dimension(480, 420));
        jP_RegistrarRes.setPreferredSize(new java.awt.Dimension(450, 420));
        jP_RegistrarRes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Responsable:");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 30));
        jP_RegistrarRes.add(jt_nomResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 240, 30));

        jLabel5.setText("Nombre del restaurante:");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));
        jP_RegistrarRes.add(jt_nombreRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 240, 30));

        jLabel6.setText("Provincia:");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 30));
        jP_RegistrarRes.add(jt_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 240, 30));

        jLabel7.setText("Localidad:");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 30));
        jP_RegistrarRes.add(jt_localidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 240, 30));

        jLabel8.setText("Dirección:");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 30));
        jP_RegistrarRes.add(jt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 240, 30));

        jLabel9.setText("* Teléfono:");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_RegistrarRes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 30));
        jP_RegistrarRes.add(jt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 240, 30));

        jb_registar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jb_registar.setText("Registrar");
        jb_registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registarActionPerformed(evt);
            }
        });
        jP_RegistrarRes.add(jb_registar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, 40));

        Restaurantes_menu.add(jP_RegistrarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jP_Confirmar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_Confirmar.setMinimumSize(new java.awt.Dimension(480, 420));
        jP_Confirmar.setPreferredSize(new java.awt.Dimension(480, 420));
        jP_Confirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Teléfono del Restaurante:");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_Confirmar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 30));
        jP_Confirmar.add(jt_telfRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 30));

        jT_ListaSinConfirm.setColumns(20);
        jT_ListaSinConfirm.setRows(5);
        jScrollPane3.setViewportView(jT_ListaSinConfirm);

        jP_Confirmar.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 220));

        jB_ConfrimarRegistro.setText("Confirmar");
        jB_ConfrimarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConfrimarRegistroActionPerformed(evt);
            }
        });
        jP_Confirmar.add(jB_ConfrimarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 40));

        jB_AgregarT.setText("Añadir teléfono");
        jB_AgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarTActionPerformed(evt);
            }
        });
        jP_Confirmar.add(jB_AgregarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 40));

        jT_listasTelefonos.setColumns(20);
        jT_listasTelefonos.setRows(5);
        jScrollPane4.setViewportView(jT_listasTelefonos);

        jP_Confirmar.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, 220));

        jLabel11.setText("Pendientes");
        jP_Confirmar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        Restaurantes_menu.add(jP_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jP_Pendientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_Pendientes.setMinimumSize(new java.awt.Dimension(480, 420));
        jP_Pendientes.setPreferredSize(new java.awt.Dimension(480, 420));
        jP_Pendientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jT_ListarPendientes.setColumns(20);
        jT_ListarPendientes.setRows(5);
        jScrollPane2.setViewportView(jT_ListarPendientes);

        jP_Pendientes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 400, 310));

        jLabel33.setText("Resaurantes Pendientes de Alta:");
        jP_Pendientes.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        Restaurantes_menu.add(jP_Pendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        JP_VerRestResp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JP_VerRestResp.setMinimumSize(new java.awt.Dimension(480, 420));
        JP_VerRestResp.setPreferredSize(new java.awt.Dimension(480, 420));
        JP_VerRestResp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_respCons.setText("Responsable:");
        jL_respCons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_VerRestResp.add(jL_respCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 30));
        JP_VerRestResp.add(JT_RESP_CONS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 230, 30));

        JT_Listar_Mis_Rest.setColumns(20);
        JT_Listar_Mis_Rest.setRows(5);
        jScrollPane5.setViewportView(JT_Listar_Mis_Rest);

        JP_VerRestResp.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 410, 240));

        jB_ConsultarResp.setText("Consultar Restaurantes");
        jB_ConsultarResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConsultarRespActionPerformed(evt);
            }
        });
        JP_VerRestResp.add(jB_ConsultarResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 230, 40));

        jLabel12.setText("Mis restaurantes");
        JP_VerRestResp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, -1));

        Restaurantes_menu.add(JP_VerRestResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jP_ActualizarDatosRest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_ActualizarDatosRest.setPreferredSize(new java.awt.Dimension(480, 420));
        jP_ActualizarDatosRest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Teléfono restaurante:");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_ActualizarDatosRest.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 30));
        jP_ActualizarDatosRest.add(jt_acTeltf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 240, 30));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jP_ActualizarDatosRest.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 150, 40));
        jP_ActualizarDatosRest.add(jt_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 240, 30));

        jLabel16.setText("Tipo Cocina:");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_ActualizarDatosRest.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 30));
        jP_ActualizarDatosRest.add(jt_tipoCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 240, 30));
        jP_ActualizarDatosRest.add(jt_precioMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, 30));

        jLabel17.setText("Precio medio:");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_ActualizarDatosRest.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, 30));

        jLabel18.setText("Horario:");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_ActualizarDatosRest.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 30));

        jLabel19.setText("Descripción:");
        jP_ActualizarDatosRest.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jT_DescripcionRes.setColumns(20);
        jT_DescripcionRes.setRows(5);
        jScrollPane6.setViewportView(jT_DescripcionRes);

        jP_ActualizarDatosRest.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 440, -1));
        jP_ActualizarDatosRest.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 440, 10));

        jLabel14.setText("Completar los datos del restaurante");
        jP_ActualizarDatosRest.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, -1));

        Restaurantes_menu.add(jP_ActualizarDatosRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        JP_imageRestaurante.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP_imageRestaurante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/tactil.jpg"))); // NOI18N
        JP_imageRestaurante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 410));

        Restaurantes_menu.add(JP_imageRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        Gestion.addTab("Restaurantes", new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icon_rest.png")), Restaurantes_menu); // NOI18N

        JP_Reservas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_Reservas.setForeground(new java.awt.Color(255, 153, 0));
        JP_Reservas.setMinimumSize(new java.awt.Dimension(800, 450));
        JP_Reservas.setPreferredSize(new java.awt.Dimension(800, 440));
        JP_Reservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_ImageReservas.setMinimumSize(new java.awt.Dimension(480, 420));
        JP_ImageReservas.setPreferredSize(new java.awt.Dimension(480, 420));
        JP_ImageReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/images/tactil.jpg"))); // NOI18N
        JP_ImageReservas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 410));

        JP_Reservas.add(JP_ImageReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 420));

        JP_SolicitarReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JP_SolicitarReserva.setMinimumSize(new java.awt.Dimension(480, 300));
        JP_SolicitarReserva.setPreferredSize(new java.awt.Dimension(480, 300));
        JP_SolicitarReserva.setVerifyInputWhenFocusTarget(false);
        JP_SolicitarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Nombre Usuario:");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 30));
        JP_SolicitarReserva.add(jt_solResNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 240, -1));

        jLabel23.setText("Correo:");
        jLabel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));
        JP_SolicitarReserva.add(jt_solReserCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 240, -1));

        jLabel24.setText("Teléfono");
        jLabel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 30));
        JP_SolicitarReserva.add(jt_solReserTelfUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 240, -1));

        jLabel25.setText("Teléfono del restaurante:");
        jLabel25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 30));
        JP_SolicitarReserva.add(jt_solReserTelfRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 240, -1));

        jLabel26.setText("Fecha: (dd/mm)");
        jLabel26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));

        jLabel27.setText("Nº de Comensales");
        jLabel27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 30));
        JP_SolicitarReserva.add(jt_minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 70, 30));
        JP_SolicitarReserva.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 440, 10));

        jLabel28.setText("Datos de Usuario");
        JP_SolicitarReserva.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, -1));

        jLabel29.setText("Datos de la reserva");
        JP_SolicitarReserva.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jC_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Noviembre", "Diciembre" }));
        JP_SolicitarReserva.add(jC_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 140, -1));

        jC_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        JP_SolicitarReserva.add(jC_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));
        JP_SolicitarReserva.add(jt_NComensales, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, 30));

        jLabel30.setText("Hora (h/m)");
        jLabel30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_SolicitarReserva.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 30));
        JP_SolicitarReserva.add(jt_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 80, 30));

        JB_SolicitarReserva.setText("Solicitar Reserva");
        JB_SolicitarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SolicitarReservaActionPerformed(evt);
            }
        });
        JP_SolicitarReserva.add(JB_SolicitarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 170, 40));

        JP_Reservas.add(JP_SolicitarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        JP_ConfirmarReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JP_ConfirmarReserva.setMinimumSize(new java.awt.Dimension(480, 300));
        JP_ConfirmarReserva.setPreferredSize(new java.awt.Dimension(480, 300));
        JP_ConfirmarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("COD- Reserva:");
        jLabel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_ConfirmarReserva.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, 30));
        JP_ConfirmarReserva.add(jt_confReserCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 240, 30));

        jLabel32.setText("Teléfono del Restaurante:");
        jLabel32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JP_ConfirmarReserva.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 30));

        jt_confResrTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_confResrTelfActionPerformed(evt);
            }
        });
        JP_ConfirmarReserva.add(jt_confResrTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 240, 30));

        jB_ConfirmarReserva.setText("Confirmar Reserva");
        jB_ConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConfirmarReservaActionPerformed(evt);
            }
        });
        JP_ConfirmarReserva.add(jB_ConfirmarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 240, 40));

        JP_Reservas.add(JP_ConfirmarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jP_verReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_verReserva.setMinimumSize(new java.awt.Dimension(480, 400));
        jP_verReserva.setOpaque(false);
        jP_verReserva.setPreferredSize(new java.awt.Dimension(480, 400));
        jP_verReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_verResrTelf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_verResrTelf1ActionPerformed(evt);
            }
        });
        jP_verReserva.add(jt_verResrTelf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 220, 30));

        jLabel35.setText("Teléfono del Usuario:");
        jLabel35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_verReserva.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 30));

        jB_VerReserva.setText("Ver Reserva");
        jB_VerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VerReservaActionPerformed(evt);
            }
        });
        jP_verReserva.add(jB_VerReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, 40));

        jT_verReserSel.setColumns(20);
        jT_verReserSel.setRows(5);
        jScrollPane8.setViewportView(jT_verReserSel);

        jP_verReserva.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 420, 230));

        jLabel36.setText("Reserva ");
        jP_verReserva.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, 20));

        JP_Reservas.add(jP_verReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jP_AnularReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jP_AnularReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("COD- Reserva:");
        jLabel34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_AnularReserva.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 30));

        jt_AnularReserCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_AnularReserCodigoActionPerformed(evt);
            }
        });
        jP_AnularReserva.add(jt_AnularReserCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 240, 30));

        jB_AnularRes.setText("Anular  Reserva");
        jB_AnularRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AnularResActionPerformed(evt);
            }
        });
        jP_AnularReserva.add(jB_AnularRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 40));

        jLabel37.setText("Teléfono Usuario");
        jLabel37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jP_AnularReserva.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        jt_AnularResertelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_AnularResertelefonoActionPerformed(evt);
            }
        });
        jP_AnularReserva.add(jt_AnularResertelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 240, 30));

        JP_Reservas.add(jP_AnularReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 420));

        jb_ConfirmarReserva.setText("Confirmar Reserva");
        jb_ConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ConfirmarReservaActionPerformed(evt);
            }
        });
        JP_Reservas.add(jb_ConfirmarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 250, 60));

        jb_VerReservas.setText("Ver Reservas de un Usuario");
        jb_VerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VerReservasActionPerformed(evt);
            }
        });
        JP_Reservas.add(jb_VerReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, 60));

        jb_AnularReserva.setText("Anular Reserva");
        jb_AnularReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AnularReservaActionPerformed(evt);
            }
        });
        JP_Reservas.add(jb_AnularReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, 60));

        jb_AnularReservasPasadas.setText("Anular Reservas Pasadas");
        jb_AnularReservasPasadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AnularReservasPasadasActionPerformed(evt);
            }
        });
        JP_Reservas.add(jb_AnularReservasPasadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 250, 60));

        jb_SolicitarReserva.setText("Solicitar Reserva");
        jb_SolicitarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SolicitarReservaActionPerformed(evt);
            }
        });
        JP_Reservas.add(jb_SolicitarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 250, 60));

        Gestion.addTab("Reservas", new javax.swing.ImageIcon(getClass().getResource("/Gui/images/icon_reserva.png")), JP_Reservas); // NOI18N

        getContentPane().add(Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 830, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //=============================================================================
    //                  RESPONSABLES
    //============================================================================
    private void CrearResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearResponsableActionPerformed
        
         this.jp_DarAlta.setVisible(true);
         this.jp_ListarRes.setVisible(false);
        this.jp_imageResponsables.setVisible(false);
         
    }//GEN-LAST:event_CrearResponsableActionPerformed

    private void jb_listaResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listaResActionPerformed
       ArrayList lista =aComer.verResponsables();
       String cadena="";
       for(int i=0;i<lista.size();i++){
           cadena = cadena +lista.get(i).toString();
           cadena = cadena +"\n=============================================\n";
       }
       this.jT_listarRes.setText(cadena);
       this.jp_ListarRes.setVisible(true);
       this.jp_DarAlta.setVisible(false);
       
        this.jp_imageResponsables.setVisible(false);
    }//GEN-LAST:event_jb_listaResActionPerformed

    private void resgistrarResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgistrarResponsableActionPerformed
       String nombre = this.jt_nombreRes.getText();
       String clave = this.jt_ClaveRes.getText();
       String correo = this.jt_CorreoRes.getText();
        if(nombre.equals("") || clave.equals("")||correo.equals("")){
            JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campos");
            
        }else{
           aComer.altaRegistro(nombre,clave , correo,"Responsable");
           this.jt_nombreRes.setText("");
           this.jt_ClaveRes.setText("");
           this.jt_CorreoRes.setText("");
           JOptionPane.showMessageDialog(null, "El registro de ha realizado con éxito");
           
        }
    }//GEN-LAST:event_resgistrarResponsableActionPerformed
    //=============================================================================
    //                  RESTAURANTES
    //============================================================================
    private void jb_verResPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verResPendientesActionPerformed
        this.jP_RegistrarRes.setVisible(false);
         this.JP_VerRestResp.setVisible(false);         
        this.jP_Confirmar.setVisible(false);
        this.jP_ActualizarDatosRest.setVisible(false);
        this.JP_imageRestaurante.setVisible(false);
        this.jP_Pendientes.setVisible(true);
        
        List<Restaurante> list = aComer.obtenerRestaurantesPendientesDeAlta();
        String c="";
        if(!list.isEmpty()){
            c=    "\n=============================================\n";
            for (Object list1 : list) {
                c = c + list1.toString();
                c= c+"\n=============================================\n";
            }
        }
        this.jT_ListarPendientes.setText(c);
        
    }//GEN-LAST:event_jb_verResPendientesActionPerformed

    private void jb_confirmarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_confirmarRegActionPerformed
        this.jP_RegistrarRes.setVisible(false);
        this.jP_Pendientes.setVisible(false);        
        this.JP_VerRestResp.setVisible(false);
        this.jP_ActualizarDatosRest.setVisible(false);
        this.JP_imageRestaurante.setVisible(false);
        List<Restaurante> list = aComer.obtenerRestaurantesPendientesDeAlta();
        String c="";
        if(!list.isEmpty()){
            c=    "\n=============================================\n";
            for (Object list1 : list) {
                c = c + list1.toString();
                c= c+"\n=============================================\n";
            }
        }
        this.jT_ListaSinConfirm.setText(c);
        
        this.jP_Confirmar.setVisible(true);
    }//GEN-LAST:event_jb_confirmarRegActionPerformed

    private void jb_consultarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_consultarResActionPerformed
        this.jP_RegistrarRes.setVisible(false);
        this.jP_Pendientes.setVisible(false);
        this.jP_Confirmar.setVisible(false);        
        this.jP_ActualizarDatosRest.setVisible(false);
        this.JP_imageRestaurante.setVisible(false);
        this.JP_VerRestResp.setVisible(true);
        this.JT_Listar_Mis_Rest.setText("");
        this.JT_RESP_CONS.setText("");
    }//GEN-LAST:event_jb_consultarResActionPerformed

    private void jb_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ActualizarActionPerformed
        this.jP_RegistrarRes.setVisible(false);
        this.jP_Pendientes.setVisible(false);        
        this.jP_Confirmar.setVisible(false);
        this.jP_ActualizarDatosRest.setVisible(true);
        
        this.JP_VerRestResp.setVisible(false);    
        this.JP_imageRestaurante.setVisible(false);
    }//GEN-LAST:event_jb_ActualizarActionPerformed

    private void jb_RegistrarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_RegistrarResActionPerformed
       this.jP_RegistrarRes.setVisible(true);
       
        this.jP_Pendientes.setVisible(false);
        this.jP_Confirmar.setVisible(false);
        this.jP_ActualizarDatosRest.setVisible(false);
        this.JP_imageRestaurante.setVisible(false);      
    }//GEN-LAST:event_jb_RegistrarResActionPerformed

    private void jb_registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registarActionPerformed
        String nombreRes, nombreRest,localidad,provincia,telefono,direccion;
        
        nombreRes= this.jt_nomResp.getText();
        nombreRest= this.jt_nombreRest.getText();
        localidad = this.jt_localidad.getText();
        direccion =  this.jt_direccion.getText();
        provincia = this.jt_provincia.getText();
        telefono = this.jt_telefono.getText();
        
            try {
                if(nombreRes.equals("")||nombreRest.equals("")|| 
                   localidad.equals("")|| direccion.equals("")||
                   provincia.equals("")||telefono.equals("")){
                    
                    JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campo ");
                }
                else{
                    aComer.solicitarRegistroRestaurante(nombreRes, nombreRest, provincia, localidad, direccion, telefono);
                    JOptionPane.showMessageDialog(null, "El registro se ha realizado con éxito");
                    this.jt_nomResp.setText("");
                    this.jt_nombreRest.setText("");
                    this.jt_localidad.setText("");
                    this.jt_direccion.setText("");
                    this.jt_provincia.setText("");
                    this.jt_telefono.setText("");
                }
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex);               
            }
            
    }//GEN-LAST:event_jb_registarActionPerformed

    private void jB_ConsultarRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConsultarRespActionPerformed
       String respon=this.JT_RESP_CONS.getText();
        String e="";
        List list;
       this.JT_Listar_Mis_Rest.setText(e);
        if(respon.equals("")){
            JOptionPane.showMessageDialog(null, "Es necesario el nombre del responsable.");
        }else{            
             list= aComer.obtenerMisRestaurantes(respon);
            if(!list.isEmpty()){
               String c="";
                for (Object list1 : list) {
                      c = c + list1;
                      c= c+"\n===================\n";
                }
                this.JT_Listar_Mis_Rest.setText(c);
                this.JT_RESP_CONS.setText("");
                list.clear();
            }else JOptionPane.showMessageDialog(null, "El Responsable no se encuentra resgistrado.");
        }
    }//GEN-LAST:event_jB_ConsultarRespActionPerformed

    private void jB_AgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarTActionPerformed
      String tRest = this.jt_telfRestaurante.getText();
      if(tRest.equals("")){
          JOptionPane.showMessageDialog(null, "Es necesario el ingresar el telefono(s) del restaurante.");
      }
      else{
          this.listaTelefonos.add(tRest);
          String c="";
          for (Object list1 : this.listaTelefonos) {
                c = c + list1;
                c= c+"\n===================\n";
            }
          this.jT_listasTelefonos.setText(c);
          this.jt_telfRestaurante.setText("");
      }
    }//GEN-LAST:event_jB_AgregarTActionPerformed

    private void jB_ConfrimarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConfrimarRegistroActionPerformed
        if(!this.listaTelefonos.isEmpty()){            
            aComer.confirmarRegistroDeRestaurante(this.listaTelefonos);
             JOptionPane.showMessageDialog(null, "La operación se ha realizado con éxito. ");
        } 
         List<Restaurante> list = aComer.obtenerRestaurantesPendientesDeAlta();
         if(!list.isEmpty()){
             
             String c=    "\n==============================\n";
            for (Object list1 : list) {
                c = c + list1.toString();
                c= c+"\n===================================\n";
            }
            this.jT_ListaSinConfirm.setText(c);
         }else this.jT_ListaSinConfirm.setText("");
         
        this.listaTelefonos.clear();
        this.jT_listasTelefonos.setText("");
    }//GEN-LAST:event_jB_ConfrimarRegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String telf ,descripcion,tipoCocina, horario;
       
       telf= this.jt_acTeltf.getText();
       descripcion = this.jT_DescripcionRes.getText();
       tipoCocina=this.jt_tipoCocina.getText();
       horario=this.jt_horario.getText();
       float precio = 0;
       if(!telf.equals("")){
            precio = Float.parseFloat(telf) ;
            if(descripcion.equals("")||tipoCocina.equals("")||horario.equals("")){
                JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campo ");
            }else{
                try {
                    aComer.actualizarDatosRestaurante(telf,"", telf, tipoCocina, precio, descripcion, horario);
                    JOptionPane.showMessageDialog(null, "La operación se ha realizado con éxito. ");
                    this.jt_acTeltf.setText("");
                    this.jT_DescripcionRes.setText("");
                    this.jt_tipoCocina.setText("");
                    this.jt_horario.setText("");
                    this.jt_precioMedio.setText("");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }       
       }else JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campo ");
    }//GEN-LAST:event_jButton1ActionPerformed
    //=============================================================================
    //                  RESERVAS
    //============================================================================
    private void jb_SolicitarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SolicitarReservaActionPerformed
      this.JP_ImageReservas.setVisible(false);
      this.jP_verReserva.setVisible(false);
      this.JP_ConfirmarReserva.setVisible(false);
      this.jP_AnularReserva.setVisible(false);
      this.JP_SolicitarReserva.setVisible(true);
    }//GEN-LAST:event_jb_SolicitarReservaActionPerformed

    private void jb_ConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ConfirmarReservaActionPerformed
        this.JP_ImageReservas.setVisible(false);
        this.JP_SolicitarReserva.setVisible(false);
        this.jP_verReserva.setVisible(false);         
        this.jP_AnularReserva.setVisible(false);
      
        this.JP_ConfirmarReserva.setVisible(true);
    }//GEN-LAST:event_jb_ConfirmarReservaActionPerformed

    private void jb_VerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VerReservasActionPerformed
        this.JP_ImageReservas.setVisible(false);
        this.JP_SolicitarReserva.setVisible(false); 
        this.JP_ConfirmarReserva.setVisible(false);
        this.jP_AnularReserva.setVisible(false);
      
        this.jT_verReserSel.setText("");
        this.jt_verResrTelf1.setText("");
        this.jP_verReserva.setVisible(true);
    }//GEN-LAST:event_jb_VerReservasActionPerformed

    private void jb_AnularReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AnularReservaActionPerformed
        this.JP_ImageReservas.setVisible(false);
        this.JP_SolicitarReserva.setVisible(false);
        this.jP_verReserva.setVisible(false);
        this.JP_ConfirmarReserva.setVisible(false);
      
        this.jP_AnularReserva.setVisible(true);
    }//GEN-LAST:event_jb_AnularReservaActionPerformed
/**
 * 
 * @param evt 
 */
    private void jb_AnularReservasPasadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AnularReservasPasadasActionPerformed
        this.JP_ImageReservas.setVisible(true);
        this.JP_SolicitarReserva.setVisible(false);
        this.jP_verReserva.setVisible(false);
        this.JP_ConfirmarReserva.setVisible(false);
        this.jP_AnularReserva.setVisible(false);
        
        aComer.eliminarReservasPasadasClientesNoHabituales();
        JOptionPane.showMessageDialog(null, "La operación se ha realizado con éxito. ");
    }//GEN-LAST:event_jb_AnularReservasPasadasActionPerformed
/**
 * 
 * @param evt 
 */
    private void JB_SolicitarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SolicitarReservaActionPerformed
        String telefonoU, telefonoR,nombreU,correoU,dia,mes,hora,minutos;
        int numComensales ;
        int _dia,_hora,_mes,_minutos;
                telefonoU= this.jt_solReserTelfUs.getText();
                telefonoR = this.jt_solReserTelfRes.getText();
                nombreU= this.jt_solResNombreU.getText();
                correoU = this.jt_solReserCorreo.getText();
                dia = (String) this.jC_dia.getSelectedItem();
                _dia = Integer.parseInt(dia);
                mes = this.jC_mes.getSelectedItem().toString();         
               
                _mes = this.obtenerMes(mes);               
                
                hora= this.jt_Hora.getText();
                minutos = this.jt_minutos.getText();                
                
        if(nombreU.equals("")||correoU.equals("")|| telefonoU.equals("")|| 
                telefonoR.equals("")|| dia.equals("")||mes.equals("")||
            hora.equals("")||minutos.equals("")||this.jt_NComensales.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campo ");
        } else{
                _hora = Integer.parseInt(hora);
                _minutos = Integer.parseInt(minutos);
             numComensales = Integer.parseInt(this.jt_NComensales.getText());
            GregorianCalendar fecha = new GregorianCalendar(2015,_mes-1,_dia,_hora,_minutos);                    
            aComer.solicitarReservaRestaurante(nombreU, correoU, telefonoU, telefonoR, fecha, numComensales);
             JOptionPane.showMessageDialog(null, "La operación se ha realizado con éxito. ");
            this.jt_solResNombreU.setText("");
            this.jt_solReserCorreo.setText("");
            this.jt_solReserTelfRes.setText("");
            this.jt_solReserTelfUs.setText("");
            this.jt_NComensales.setText("");
            this.jt_Hora.setText("");
            this.jt_minutos.setText("");
        }            
    }//GEN-LAST:event_JB_SolicitarReservaActionPerformed
/**
 * 
 * @param evt 
 */
    private void jB_ConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConfirmarReservaActionPerformed
       String codigo,telefono ;
       codigo = this.jt_confReserCodigo.getText();
       telefono = this.jt_confResrTelf.getText();
       if(codigo.equals("")||telefono.equals("")){
           
       }else{
           aComer.confirmarReserva(codigo, telefono);
           this.jt_confReserCodigo.setText("");
           this.jt_confResrTelf.setText("");
           
           
       }
    }//GEN-LAST:event_jB_ConfirmarReservaActionPerformed

    private void jB_VerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VerReservaActionPerformed
      String telefono = this.jt_verResrTelf1.getText();
      
        List list= new ArrayList();
         String c= "";
         this.jT_verReserSel.setText(c);
            try {
                list = aComer.consultarMisReservas(telefono);
            } catch (Exception ex) {
                this.jt_verResrTelf1.setText("");
                JOptionPane.showMessageDialog(null, ex);
            }
       //==============================================================================>>>>>>>>>>>>>>>>>>>
            if(!list.isEmpty()){             
                c= c+   "\n==============================\n";
               for (Object list1 : list) {
                   c = c + list1.toString();
                   c= c+"\n===================================\n";
               }
            }
            this.jT_verReserSel.setText(c);
              this.jt_verResrTelf1.setText("");  
    }//GEN-LAST:event_jB_VerReservaActionPerformed

    private void jt_confResrTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_confResrTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_confResrTelfActionPerformed

    private void jB_AnularResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AnularResActionPerformed
        String codigo = this.jt_AnularReserCodigo.getText();
        String telefono = this.jt_AnularResertelefono.getText();
       
        if(codigo.equals("")|| telefono.equals("")){
             JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los campo.");
        }else
        {
            
                aComer.anularReserva(codigo, telefono);
                
                JOptionPane.showMessageDialog(null, "La operación se ha realizado con exito");
                
            
            this.jt_AnularReserCodigo.setText("");
            this.jt_AnularResertelefono.setText("");
        }
    }//GEN-LAST:event_jB_AnularResActionPerformed

    private void jt_AnularReserCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_AnularReserCodigoActionPerformed
        
    }//GEN-LAST:event_jt_AnularReserCodigoActionPerformed

    private void jt_AnularResertelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_AnularResertelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_AnularResertelefonoActionPerformed

    private void jt_verResrTelf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_verResrTelf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_verResrTelf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuenProvecho_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BuenProvecho_GUI().setVisible(true);
            }
        });
    }
    /**
     * Devuelve un entero identificando el mes
     * @param mes String
     * @return int
     */
    public int obtenerMes(String mes){
        int _mes=-1;
         switch(mes){
                        case "Enero":
                            _mes = 1;
                            break;                    
                        case "Febrero":
                            _mes = 2;
                            break;
                        case "Marzo":
                            _mes = 3;
                            break;
                        case "Abril":
                            _mes = 4;
                            break;
                        case "Mayo":
                            _mes = 5;
                            break;
                        case "Junio":
                            _mes = 6;
                            break; 
                        case "Julio":
                            _mes = 7;
                            break; 
                        case "Agosto":
                            _mes = 8;
                            break; 
                        case "Septiembre":
                            _mes = 6;
                            break; 
                        case "Octubre":
                            _mes = 9;
                            break; 
                        case "Noviembre":
                            _mes = 10;
                            break; 
                        case "Diciembre":
                            _mes = 6;
                            break; 
                    }
         return _mes;
    }
/**
 * cambia el atributo de visibilidad a false
 */
    private void invisible(){
        
        //--------------RESPONSABLES-----------------------
        this.jp_DarAlta.setVisible(false);
        this.jp_ListarRes.setVisible(false);        
        this.JP_ImageReservas.setVisible(true);
        
        //---------------RESTAURANTES----------------------
        this.jP_ActualizarDatosRest.setVisible(false);        
        this.jP_RegistrarRes.setVisible(false);
        this.jP_Pendientes.setVisible(false);
        this.jP_Confirmar.setVisible(false);
        this.JP_VerRestResp.setVisible(false);
        this.JP_imageRestaurante.setVisible(true);  
        
        //----------------RESERVAS--------------------------
        this.jP_verReserva.setVisible(false);
        this.JP_ConfirmarReserva.setVisible(false);
        this.jP_AnularReserva.setVisible(false);
        this.JP_SolicitarReserva.setVisible(false);        
        this.JP_ImageReservas.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearResponsable;
    private javax.swing.JTabbedPane Gestion;
    private javax.swing.JButton JB_SolicitarReserva;
    private javax.swing.JPanel JP_ConfirmarReserva;
    private javax.swing.JPanel JP_ImageReservas;
    private javax.swing.JPanel JP_Reservas;
    private javax.swing.JPanel JP_Responsables;
    private javax.swing.JPanel JP_SolicitarReserva;
    private javax.swing.JPanel JP_VerRestResp;
    private javax.swing.JPanel JP_imageRestaurante;
    private javax.swing.JTextArea JT_Listar_Mis_Rest;
    private javax.swing.JTextField JT_RESP_CONS;
    private javax.swing.JPanel Restaurantes_menu;
    private javax.swing.JButton jB_AgregarT;
    private javax.swing.JButton jB_AnularRes;
    private javax.swing.JButton jB_ConfirmarReserva;
    private javax.swing.JButton jB_ConfrimarRegistro;
    private javax.swing.JButton jB_ConsultarResp;
    private javax.swing.JButton jB_VerReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jC_dia;
    private javax.swing.JComboBox jC_mes;
    private javax.swing.JLabel jL_respCons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_ActualizarDatosRest;
    private javax.swing.JPanel jP_AnularReserva;
    private javax.swing.JPanel jP_Confirmar;
    private javax.swing.JPanel jP_Pendientes;
    private javax.swing.JPanel jP_RegistrarRes;
    private javax.swing.JPanel jP_verReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jT_DescripcionRes;
    private javax.swing.JTextArea jT_ListaSinConfirm;
    private javax.swing.JTextArea jT_ListarPendientes;
    private javax.swing.JTextArea jT_listarRes;
    private javax.swing.JTextArea jT_listasTelefonos;
    private javax.swing.JTextArea jT_verReserSel;
    private javax.swing.JButton jb_Actualizar;
    private javax.swing.JButton jb_AnularReserva;
    private javax.swing.JButton jb_AnularReservasPasadas;
    private javax.swing.JButton jb_ConfirmarReserva;
    private javax.swing.JButton jb_RegistrarRes;
    private javax.swing.JButton jb_SolicitarReserva;
    private javax.swing.JButton jb_VerReservas;
    private javax.swing.JButton jb_confirmarReg;
    private javax.swing.JButton jb_consultarRes;
    private javax.swing.JButton jb_listaRes;
    private javax.swing.JButton jb_registar;
    private javax.swing.JButton jb_verResPendientes;
    private javax.swing.JPanel jp_DarAlta;
    private javax.swing.JPanel jp_ListarRes;
    private javax.swing.JPanel jp_imageResponsables;
    private javax.swing.JTextField jt_AnularReserCodigo;
    private javax.swing.JTextField jt_AnularResertelefono;
    private javax.swing.JTextField jt_ClaveRes;
    private javax.swing.JTextField jt_CorreoRes;
    private javax.swing.JTextField jt_Hora;
    private javax.swing.JTextField jt_NComensales;
    private javax.swing.JTextField jt_acTeltf;
    private javax.swing.JTextField jt_confReserCodigo;
    private javax.swing.JTextField jt_confResrTelf;
    private javax.swing.JTextField jt_direccion;
    private javax.swing.JTextField jt_horario;
    private javax.swing.JTextField jt_localidad;
    private javax.swing.JTextField jt_minutos;
    private javax.swing.JTextField jt_nomResp;
    private javax.swing.JTextField jt_nombreRes;
    private javax.swing.JTextField jt_nombreRest;
    private javax.swing.JTextField jt_precioMedio;
    private javax.swing.JTextField jt_provincia;
    private javax.swing.JTextField jt_solResNombreU;
    private javax.swing.JTextField jt_solReserCorreo;
    private javax.swing.JTextField jt_solReserTelfRes;
    private javax.swing.JTextField jt_solReserTelfUs;
    private javax.swing.JTextField jt_telefono;
    private javax.swing.JTextField jt_telfRestaurante;
    private javax.swing.JTextField jt_tipoCocina;
    private javax.swing.JTextField jt_verResrTelf1;
    private javax.swing.JButton resgistrarResponsable;
    // End of variables declaration//GEN-END:variables
}
